[[assembly]]
name = "UltravioletRT"
kind = "library"
link_kind = "static"
root = "Runtime"

[[assembly]]
name = "UltravioletCompiler"
kind = "library"
link_kind = "static"
root = "Compiler"

[[assembly]]
name = "uv"
kind = "executable"
root = "Tools/Uv"
