[[assembly]]
name = "UltravioletRT"
kind = "library"
link_kind = "static"
root = "Source/Runtime"

[[assembly]]
name = "UltravioletCompiler"
kind = "library"
link_kind = "static"
root = "Source/Compiler"

[[assembly]]
name = "uv"
kind = "executable"
root = "Source/Tools/Uv"

[build]
incremental = true
progress = true
