foreach(required_var
        RUNTIME_LIB_TOOL
        RUNTIME_LLVM_AR
        RUNTIME_INPUT
        FINAL_RT_DIR
        FINAL_RT
        RUNTIME_LIBCMT_LIBRARY
        RUNTIME_KERNEL32_LIBRARY)
  if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
    message(FATAL_ERROR "Missing required Windows runtime staging variable: ${required_var}")
  endif()
endforeach()

set(RUNTIME_LIBCMT_PATH "${RUNTIME_LIBCMT_LIBRARY}")
if(NOT IS_ABSOLUTE "${RUNTIME_LIBCMT_PATH}")
  if(DEFINED ENV{LIB} AND NOT "$ENV{LIB}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{LIB}" RUNTIME_LIB_SEARCH_PATHS)
    foreach(search_dir IN LISTS RUNTIME_LIB_SEARCH_PATHS)
      if(EXISTS "${search_dir}/${RUNTIME_LIBCMT_LIBRARY}")
        set(RUNTIME_LIBCMT_PATH "${search_dir}/${RUNTIME_LIBCMT_LIBRARY}")
        break()
      endif()
    endforeach()
  endif()
endif()
if(NOT EXISTS "${RUNTIME_LIBCMT_PATH}")
  message(FATAL_ERROR
    "Failed to resolve ${RUNTIME_LIBCMT_LIBRARY} from the current MSVC LIB search path")
endif()

execute_process(
  COMMAND "${RUNTIME_LIB_TOOL}" /NOLOGO /LIST "${RUNTIME_LIBCMT_PATH}"
  RESULT_VARIABLE RUNTIME_LIBCMT_LIST_RESULT
  OUTPUT_VARIABLE RUNTIME_LIBCMT_MEMBERS
  ERROR_VARIABLE RUNTIME_LIBCMT_LIST_ERROR
)
if(NOT RUNTIME_LIBCMT_LIST_RESULT EQUAL 0)
  message(FATAL_ERROR
    "Failed to list libcmt members from ${RUNTIME_LIBCMT_PATH}: ${RUNTIME_LIBCMT_LIST_ERROR}")
endif()

string(REGEX MATCH "[^\\r\\n]*chkstk\\.obj" RUNTIME_LIBCMT_CHKSTK_MEMBER
       "${RUNTIME_LIBCMT_MEMBERS}")
string(REGEX MATCH "[^\\r\\n]*chkstk2\\.obj" RUNTIME_LIBCMT_CHKSTK2_MEMBER
       "${RUNTIME_LIBCMT_MEMBERS}")
if(RUNTIME_LIBCMT_CHKSTK_MEMBER STREQUAL "")
  message(FATAL_ERROR
    "Failed to locate chkstk.obj in ${RUNTIME_LIBCMT_PATH}")
endif()

file(MAKE_DIRECTORY "${FINAL_RT_DIR}")
set(RUNTIME_CRT_SHIM_DIR "${FINAL_RT_DIR}/crt_shims")
file(MAKE_DIRECTORY "${RUNTIME_CRT_SHIM_DIR}")

set(RUNTIME_CHKSTK_OBJ "${RUNTIME_CRT_SHIM_DIR}/chkstk.obj")
set(RUNTIME_CHKSTK2_OBJ "${RUNTIME_CRT_SHIM_DIR}/chkstk2.obj")
file(REMOVE "${FINAL_RT}" "${RUNTIME_CHKSTK_OBJ}" "${RUNTIME_CHKSTK2_OBJ}")

execute_process(
  COMMAND "${RUNTIME_LLVM_AR}" p "${RUNTIME_LIBCMT_PATH}"
          "${RUNTIME_LIBCMT_CHKSTK_MEMBER}"
  RESULT_VARIABLE RUNTIME_CHKSTK_EXTRACT_RESULT
  OUTPUT_FILE "${RUNTIME_CHKSTK_OBJ}"
  ERROR_VARIABLE RUNTIME_CHKSTK_EXTRACT_ERROR
)
if(NOT RUNTIME_CHKSTK_EXTRACT_RESULT EQUAL 0)
  message(FATAL_ERROR
    "Failed to extract chkstk.obj from ${RUNTIME_LIBCMT_PATH}: ${RUNTIME_CHKSTK_EXTRACT_ERROR}")
endif()

if(NOT "${RUNTIME_LIBCMT_CHKSTK2_MEMBER}" STREQUAL "")
  execute_process(
    COMMAND "${RUNTIME_LLVM_AR}" p "${RUNTIME_LIBCMT_PATH}"
            "${RUNTIME_LIBCMT_CHKSTK2_MEMBER}"
    RESULT_VARIABLE RUNTIME_CHKSTK2_EXTRACT_RESULT
    OUTPUT_FILE "${RUNTIME_CHKSTK2_OBJ}"
    ERROR_VARIABLE RUNTIME_CHKSTK2_EXTRACT_ERROR
  )
  if(NOT RUNTIME_CHKSTK2_EXTRACT_RESULT EQUAL 0)
    message(FATAL_ERROR
      "Failed to extract chkstk2.obj from ${RUNTIME_LIBCMT_PATH}: ${RUNTIME_CHKSTK2_EXTRACT_ERROR}")
  endif()
endif()

if(NOT EXISTS "${RUNTIME_CHKSTK_OBJ}")
  message(FATAL_ERROR
    "Expected extracted CRT object is missing: ${RUNTIME_CHKSTK_OBJ}")
endif()

set(RUNTIME_STAGE_INPUTS
  "${RUNTIME_INPUT}"
  "${RUNTIME_KERNEL32_LIBRARY}"
  "${RUNTIME_CHKSTK_OBJ}")
if(EXISTS "${RUNTIME_CHKSTK2_OBJ}")
  list(APPEND RUNTIME_STAGE_INPUTS "${RUNTIME_CHKSTK2_OBJ}")
endif()
if(DEFINED RUNTIME_ICU_LIBS AND NOT "${RUNTIME_ICU_LIBS}" STREQUAL "")
  list(APPEND RUNTIME_STAGE_INPUTS ${RUNTIME_ICU_LIBS})
endif()

execute_process(
  COMMAND "${RUNTIME_LIB_TOOL}" /NOLOGO "/OUT:${FINAL_RT}" ${RUNTIME_STAGE_INPUTS}
  RESULT_VARIABLE RUNTIME_STAGE_RESULT
  OUTPUT_VARIABLE RUNTIME_STAGE_OUTPUT
  ERROR_VARIABLE RUNTIME_STAGE_ERROR
)
if(NOT RUNTIME_STAGE_RESULT EQUAL 0)
  message(FATAL_ERROR
    "Failed to stage ${FINAL_RT}: ${RUNTIME_STAGE_ERROR}${RUNTIME_STAGE_OUTPUT}")
endif()

if(DEFINED RUNTIME_ICU_DLLS AND NOT "${RUNTIME_ICU_DLLS}" STREQUAL "")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different
            ${RUNTIME_ICU_DLLS}
            "${FINAL_RT_DIR}"
    RESULT_VARIABLE RUNTIME_COPY_RESULT
    OUTPUT_VARIABLE RUNTIME_COPY_OUTPUT
    ERROR_VARIABLE RUNTIME_COPY_ERROR
  )
  if(NOT RUNTIME_COPY_RESULT EQUAL 0)
    message(FATAL_ERROR
      "Failed to copy ICU runtime DLLs into ${FINAL_RT_DIR}: ${RUNTIME_COPY_ERROR}${RUNTIME_COPY_OUTPUT}")
  endif()
endif()
