#ifndef CURSIVE_RT_LANGUAGE_SYMBOLS_H
#define CURSIVE_RT_LANGUAGE_SYMBOLS_H

#ifdef CURSIVE_RT_ULTRAVIOLET_SYMBOLS

#define cursive_raw_dylib_resolve ultraviolet_raw_dylib_resolve
#define cursive_panic ultraviolet_panic

#define cursive_host_alloc ultraviolet_host_alloc
#define cursive_host_free ultraviolet_host_free
#define cursive_host_session_register ultraviolet_host_session_register
#define cursive_host_session_try_enter ultraviolet_host_session_try_enter
#define cursive_host_session_leave ultraviolet_host_session_leave
#define cursive_host_session_try_retire ultraviolet_host_session_try_retire
#define cursive_host_session_abort_live ultraviolet_host_session_abort_live
#define cursive_host_session_current_env ultraviolet_host_session_current_env
#define cursive_host_session_enter_retired ultraviolet_host_session_enter_retired
#define cursive_host_session_leave_retired ultraviolet_host_session_leave_retired
#define cursive_host_session_abort_retired ultraviolet_host_session_abort_retired

#define cursive_parallel_begin ultraviolet_parallel_begin
#define cursive_parallel_join ultraviolet_parallel_join
#define cursive_parallel_work_panic ultraviolet_parallel_work_panic
#define cursive_spawn_create ultraviolet_spawn_create
#define cursive_spawn_wait ultraviolet_spawn_wait
#define cursive_dispatch_run ultraviolet_dispatch_run
#define cursive_key_scope_enter ultraviolet_key_scope_enter
#define cursive_key_scope_exit ultraviolet_key_scope_exit
#define cursive_key_check_conflict ultraviolet_key_check_conflict
#define cursive_key_acquire ultraviolet_key_acquire
#define cursive_key_release_one ultraviolet_key_release_one
#define cursive_key_release_all ultraviolet_key_release_all
#define cursive_key_reacquire_one ultraviolet_key_reacquire_one
#define cursive_key_reacquire ultraviolet_key_reacquire
#define cursive_key_release_snapshot_discard ultraviolet_key_release_snapshot_discard
#define cursive_cancel_token_new ultraviolet_cancel_token_new
#define cursive_cancel_token_cancel ultraviolet_cancel_token_cancel
#define cursive_cancel_token_is_cancelled ultraviolet_cancel_token_is_cancelled

#define cursive_x3a_x3aruntime_x3a_x3apanic ultraviolet_x3a_x3aruntime_x3a_x3apanic
#define cursive_x3a_x3aruntime_x3a_x3acontext_x5finit ultraviolet_x3a_x3aruntime_x3a_x3acontext_x5finit

#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fint ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fint
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbool ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbool
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5ffloat ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5ffloat
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fptr ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fptr
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fstring ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fstring
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fstring_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fstring_x5fmanaged
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbytes ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbytes
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbytes_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aemit_x5fbytes_x5fmanaged
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5fsink ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5fsink
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5froot ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5froot
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5flog_x5ffilter ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5flog_x5ffilter
#define cursive_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5fmin_x5flevel ultraviolet_x3a_x3aruntime_x3a_x3aconformance_x3a_x3aset_x5fmin_x5flevel

#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3anew_x5fscoped ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3anew_x5fscoped
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3aalloc ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3aalloc
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3amark ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3amark
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3areset_x5fto ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3areset_x5fto
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3areset_x5funchecked ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3areset_x5funchecked
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3afreeze ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3afreeze
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3athaw ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3athaw
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3afree_x5funchecked ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3afree_x5funchecked
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5fis_x5factive ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5fis_x5factive
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5ftag_x5ffrom ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5ftag_x5ffrom
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3ascope_x5fenter ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3ascope_x5fenter
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3ascope_x5fexit ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3ascope_x5fexit
#define cursive_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5ftag_x5fscope ultraviolet_x3a_x3aruntime_x3a_x3aregion_x3a_x3aaddr_x5ftag_x5fscope

#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3afrom ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3afrom
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3aas_x5fview ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3aas_x5fview
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3aslice ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3aslice
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3ato_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3ato_x5fmanaged
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3aclone_x5fwith ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3aclone_x5fwith
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3aappend ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3aappend
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3alength ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3alength
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3ais_x5fempty ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3ais_x5fempty
#define cursive_x3a_x3aruntime_x3a_x3astring_x3a_x3adrop_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3astring_x3a_x3adrop_x5fmanaged

#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3awith_x5fcapacity ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3awith_x5fcapacity
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3afrom_x5fslice ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3afrom_x5fslice
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3aas_x5fview ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3aas_x5fview
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3ato_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3ato_x5fmanaged
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3aview ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3aview
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3aas_x5fslice ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3aas_x5fslice
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3aview_x5fstring ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3aview_x5fstring
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3aappend ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3aappend
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3alength ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3alength
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3ais_x5fempty ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3ais_x5fempty
#define cursive_x3a_x3aruntime_x3a_x3abytes_x3a_x3adrop_x5fmanaged ultraviolet_x3a_x3aruntime_x3a_x3abytes_x3a_x3adrop_x5fmanaged

#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fread ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fread
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fwrite ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fwrite
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fappend ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fappend
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3acreate_x5fwrite ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3acreate_x5fwrite
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aread_x5ffile ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aread_x5ffile
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aread_x5fbytes ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aread_x5fbytes
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5ffile ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5ffile
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5fstdout ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5fstdout
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5fstderr ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3awrite_x5fstderr
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aexists ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aexists
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aremove ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aremove
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fdir ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aopen_x5fdir
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3acreate_x5fdir ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3acreate_x5fdir
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3aensure_x5fdir ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3aensure_x5fdir
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3akind ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3akind
#define cursive_x3a_x3aruntime_x3a_x3afs_x3a_x3arestrict ultraviolet_x3a_x3aruntime_x3a_x3afs_x3a_x3arestrict

#define cursive_x3a_x3aruntime_x3a_x3anet_x3a_x3arestrict_x5fto_x5fhost ultraviolet_x3a_x3aruntime_x3a_x3anet_x3a_x3arestrict_x5fto_x5fhost

#define cursive_x3a_x3aruntime_x3a_x3aheap_x3a_x3awith_x5fquota ultraviolet_x3a_x3aruntime_x3a_x3aheap_x3a_x3awith_x5fquota
#define cursive_x3a_x3aruntime_x3a_x3aheap_x3a_x3aalloc_x5fraw ultraviolet_x3a_x3aruntime_x3a_x3aheap_x3a_x3aalloc_x5fraw
#define cursive_x3a_x3aruntime_x3a_x3aheap_x3a_x3adealloc_x5fraw ultraviolet_x3a_x3aruntime_x3a_x3aheap_x3a_x3adealloc_x5fraw

#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3awall ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3awall
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fnow ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fnow
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fresolution ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fresolution
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5felapsed ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5felapsed
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fcoarsen ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3amonotonic_x5fcoarsen
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fnow_x5futc ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fnow_x5futc
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fresolution ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fresolution
#define cursive_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fcoarsen ultraviolet_x3a_x3aruntime_x3a_x3atime_x3a_x3awall_x5fcoarsen

#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3aexit ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3aexit
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3aget_x5fenv ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3aget_x5fenv
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3aexecutable_x5fpath ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3aexecutable_x5fpath
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3aargument_x5fcount ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3aargument_x5fcount
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3aargument ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3aargument
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3acurrent_x5fdirectory ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3acurrent_x5fdirectory
#define cursive_x3a_x3aruntime_x3a_x3asystem_x3a_x3arun ultraviolet_x3a_x3aruntime_x3a_x3asystem_x3a_x3arun

#define cursive_x3a_x3aruntime_x3a_x3acontext_x3a_x3acpu ultraviolet_x3a_x3aruntime_x3a_x3acontext_x3a_x3acpu
#define cursive_x3a_x3aruntime_x3a_x3acontext_x3a_x3agpu ultraviolet_x3a_x3aruntime_x3a_x3acontext_x3a_x3agpu
#define cursive_x3a_x3aruntime_x3a_x3acontext_x3a_x3ainline ultraviolet_x3a_x3aruntime_x3a_x3acontext_x3a_x3ainline
#define cursive_x3a_x3aruntime_x3a_x3aexecution_x5fdomain_x3a_x3aname ultraviolet_x3a_x3aruntime_x3a_x3aexecution_x5fdomain_x3a_x3aname
#define cursive_x3a_x3aruntime_x3a_x3aexecution_x5fdomain_x3a_x3amax_x5fconcurrency ultraviolet_x3a_x3aruntime_x3a_x3aexecution_x5fdomain_x3a_x3amax_x5fconcurrency

#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3aglobal_x5fid ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3aglobal_x5fid
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3alocal_x5fid ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3alocal_x5fid
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fid ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fid
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fsize ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fsize
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3aglobal_x5fsize ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3aglobal_x5fsize
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3anum_x5fworkgroups ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3anum_x5fworkgroups
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3alinear_x5fid ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3alinear_x5fid
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3abarrier ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3abarrier
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3amemory_x5fbarrier ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3amemory_x5fbarrier
#define cursive_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fbarrier ultraviolet_x3a_x3aruntime_x3a_x3agpu_x3a_x3aworkgroup_x5fbarrier

#define cursive_x3a_x3aruntime_x3a_x3aasync_x3a_x3aalloc_x5fframe ultraviolet_x3a_x3aruntime_x3a_x3aasync_x3a_x3aalloc_x5fframe
#define cursive_x3a_x3aruntime_x3a_x3aasync_x3a_x3afree_x5fframe ultraviolet_x3a_x3aruntime_x3a_x3aasync_x3a_x3afree_x5fframe
#define cursive_x3a_x3aruntime_x3a_x3aasync_x3a_x3aresume ultraviolet_x3a_x3aruntime_x3a_x3aasync_x3a_x3aresume

#define cursive_x3a_x3aruntime_x3a_x3areactor_x3a_x3aregister ultraviolet_x3a_x3aruntime_x3a_x3areactor_x3a_x3aregister

#endif

#endif
