if(NOT DEFINED UV_CHMOD_PATH)
  message(FATAL_ERROR "UV_CHMOD_PATH is required")
endif()

if(EXISTS "${UV_CHMOD_PATH}")
  file(CHMOD "${UV_CHMOD_PATH}"
    PERMISSIONS
      OWNER_READ OWNER_WRITE OWNER_EXECUTE
      GROUP_READ GROUP_EXECUTE
      WORLD_READ WORLD_EXECUTE
  )
endif()
